### ISSUE TITLE
Setup bot to suggest help command if someone enters a command it doesnt recognize (or no command)

### ISSUE THREAD

**Issue by bmorrisondev** [fullstack-chat/fsc.bot#32]

**Comment by dmdboi** [comment]
Could possibly shorten down the help command embeds as after 3/4 commands a user's screen is full. See image below 

![image](https://user-images.githubusercontent.com/23747483/94961314-4e74c300-04ec-11eb-8bf6-7df2ae95d7d9.png)

**Comment by dmdboi** [comment]
Feature Implemented, closing issue.
